from numpy import zeros
d = 2

Scyto        = zeros(d)
MEK          = zeros(d)
MEKRAFp      = zeros(d)
MEKp         = zeros(d)
MEKpMEKPh    = zeros(d)
MEKpRAFp     = zeros(d)
MEKpp        = zeros(d)
MEKppMEKPh   = zeros(d)
MAPK         = zeros(d)
MAPKMEKpp    = zeros(d)
MAPKp        = zeros(d)
MAPKpMEKpp   = zeros(d)
MAPKpp       = zeros(d)
MAPKpMAPKPh  = zeros(d)
MAPKppMAPKPh = zeros(d)
C1           = zeros(d)
C2           = zeros(d)
C3           = zeros(d)
C4           = zeros(d)
C5           = zeros(d)
C6           = zeros(d)
C7           = zeros(d)
C8           = zeros(d)
C9           = zeros(d)
Smem         = zeros(d)

