from numpy import zeros
d = 2

scyto        = zeros(d)
mek          = zeros(d)
mekrafp      = zeros(d)
mekp         = zeros(d)
mekpmekph    = zeros(d)
mekprafp     = zeros(d)
mekpp        = zeros(d)
mekppmekph   = zeros(d)
mapk         = zeros(d)
mapkmekpp    = zeros(d)
mapkp        = zeros(d)
mapkpmekpp   = zeros(d)
mapkpp       = zeros(d)
mapkpmapkph  = zeros(d)
mapkppmapkph = zeros(d)
c1           = zeros(d)
c2           = zeros(d)
c3           = zeros(d)
c4           = zeros(d)
c5           = zeros(d)
c6           = zeros(d)
c7           = zeros(d)
c8           = zeros(d)
c9           = zeros(d)
Smem         = zeros(d)

